ALTER TABLE skills ADD COLUMN delivery_type TEXT NOT NULL DEFAULT 'paid_api';
ALTER TABLE skills ADD COLUMN listing_kind TEXT NOT NULL DEFAULT 'publisher';
ALTER TABLE skills ADD COLUMN publisher_verified INTEGER NOT NULL DEFAULT 0;
ALTER TABLE skills ADD COLUMN source_url TEXT;
ALTER TABLE skills ADD COLUMN source_commit TEXT;
ALTER TABLE skills ADD COLUMN source_path TEXT;

UPDATE skills
SET listing_kind = 'platform', publisher_verified = 1
WHERE publisher_name = 'GOKUI Labs';

INSERT OR IGNORE INTO skills (
  id, slug, title, description, category, tags_json, version, license,
  publisher_name, skill_markdown, runner, price_usd, risk_level, risk_summary,
  status, invokes, created_at, updated_at, delivery_type, listing_kind,
  publisher_verified, source_url, source_commit, source_path
) VALUES
(
  'curated_vercel_react_best_practices_4559f18',
  'vercel-react-best-practices',
  'React Performance Playbook',
  'Applies Vercel Engineering guidance to React and Next.js code, with prioritized rules for data fetching, bundles, rendering, and rerenders.',
  'Web development',
  '["react","nextjs","performance","vercel"]',
  '1.0.0',
  'MIT',
  'Vercel',
  'GOKUI community-curated source listing. Open the pinned upstream package to review and install the complete skill.',
  'external_source',
  '0.00',
  'normal',
  'Instruction and reference package; no bundled executable scripts found in the reviewed version.',
  'approved',
  0,
  '2026-07-22T00:00:00.000Z',
  '2026-07-21T00:42:47.000Z',
  'external_source',
  'curated',
  0,
  'https://github.com/vercel-labs/agent-skills/tree/4559f18a20c1691c744b4395194290db6a0df5e9/skills/react-best-practices',
  '4559f18a20c1691c744b4395194290db6a0df5e9',
  'skills/react-best-practices'
),
(
  'curated_vercel_composition_patterns_4559f18',
  'vercel-composition-patterns',
  'Scalable React Composition',
  'Refactors rigid React components into flexible APIs using compound components, lifted state, explicit variants, and React 19 patterns.',
  'Web development',
  '["react","components","architecture","vercel"]',
  '1.0.0',
  'MIT',
  'Vercel',
  'GOKUI community-curated source listing. Open the pinned upstream package to review and install the complete skill.',
  'external_source',
  '0.00',
  'normal',
  'Instruction and reference package; no external network fetch is required by the reviewed skill.',
  'approved',
  0,
  '2026-07-22T00:00:00.000Z',
  '2026-07-21T00:42:47.000Z',
  'external_source',
  'curated',
  0,
  'https://github.com/vercel-labs/agent-skills/tree/4559f18a20c1691c744b4395194290db6a0df5e9/skills/composition-patterns',
  '4559f18a20c1691c744b4395194290db6a0df5e9',
  'skills/composition-patterns'
),
(
  'curated_addy_web_quality_95d6e25',
  'web-quality-audit',
  'Full Web Quality Audit',
  'Reviews a site across performance, accessibility, SEO, and modern web practices using a Lighthouse-oriented checklist.',
  'Web quality',
  '["lighthouse","accessibility","seo","performance"]',
  '1.0',
  'MIT',
  'Addy Osmani',
  'GOKUI community-curated source listing. Open the pinned upstream package to review and install the complete skill.',
  'external_source',
  '0.00',
  'normal',
  'Includes one reviewed read-only shell analyzer for local HTML files; inspect bundled scripts before use.',
  'approved',
  0,
  '2026-07-22T00:00:00.000Z',
  '2026-06-14T09:08:35.000Z',
  'external_source',
  'curated',
  0,
  'https://github.com/addyosmani/web-quality-skills/tree/95d6e255afe1596b557d7a8498517884438f5b3a/skills/web-quality-audit',
  '95d6e255afe1596b557d7a8498517884438f5b3a',
  'skills/web-quality-audit'
),
(
  'curated_corey_customer_research_6726476',
  'customer-research',
  'Customer Research',
  'Turns interviews, reviews, support conversations, and public community evidence into usable customer language, needs, and buying insights.',
  'Research',
  '["customer-research","voc","jtbd","interviews"]',
  '2.0.1',
  'MIT',
  'Corey Haines',
  'GOKUI community-curated source listing. Open the pinned upstream package to review and install the complete skill.',
  'external_source',
  '0.00',
  'normal',
  'Instruction and reference package. Online research still requires source verification and privacy-aware handling of customer data.',
  'approved',
  0,
  '2026-07-22T00:00:00.000Z',
  '2026-07-16T19:07:40.000Z',
  'external_source',
  'curated',
  0,
  'https://github.com/coreyhaines31/marketingskills/tree/67264763cb107d61749f418d081c56e5bcbc0209/skills/customer-research',
  '67264763cb107d61749f418d081c56e5bcbc0209',
  'skills/customer-research'
),
(
  'curated_corey_copywriting_6726476',
  'conversion-copywriting',
  'Conversion Copywriting',
  'Writes and restructures website copy around audience context, value, evidence, objections, and a clear next action.',
  'Marketing',
  '["copywriting","landing-page","positioning","conversion"]',
  '2.0.1',
  'MIT',
  'Corey Haines',
  'GOKUI community-curated source listing. Open the pinned upstream package to review and install the complete skill.',
  'external_source',
  '0.00',
  'normal',
  'Instruction and reference package; claims and proof still require factual review before publication.',
  'approved',
  0,
  '2026-07-22T00:00:00.000Z',
  '2026-07-16T19:07:40.000Z',
  'external_source',
  'curated',
  0,
  'https://github.com/coreyhaines31/marketingskills/tree/67264763cb107d61749f418d081c56e5bcbc0209/skills/copywriting',
  '67264763cb107d61749f418d081c56e5bcbc0209',
  'skills/copywriting'
),
(
  'curated_corey_analytics_6726476',
  'analytics-tracking-plan',
  'Analytics Tracking Plan',
  'Designs practical event, conversion, attribution, and QA plans for GA4, GTM, Segment, Mixpanel, and product analytics.',
  'Analytics',
  '["analytics","ga4","gtm","events"]',
  '2.0.0',
  'MIT',
  'Corey Haines',
  'GOKUI community-curated source listing. Open the pinned upstream package to review and install the complete skill.',
  'external_source',
  '0.00',
  'caution',
  'Planning is low risk, but implementation can change production tracking and transmit user data to analytics vendors.',
  'approved',
  0,
  '2026-07-22T00:00:00.000Z',
  '2026-07-16T19:07:40.000Z',
  'external_source',
  'curated',
  0,
  'https://github.com/coreyhaines31/marketingskills/tree/67264763cb107d61749f418d081c56e5bcbc0209/skills/analytics',
  '67264763cb107d61749f418d081c56e5bcbc0209',
  'skills/analytics'
),
(
  'curated_tob_differential_review_cfe5d7b',
  'differential-security-review',
  'Differential Security Review',
  'Reviews code changes by risk, history, test coverage, blast radius, and concrete attacker scenarios instead of treating every diff equally.',
  'Security',
  '["security-review","git-diff","blast-radius","trail-of-bits"]',
  'git-cfe5d7b',
  'CC-BY-SA-4.0',
  'Trail of Bits',
  'GOKUI community-curated source listing. Open the pinned upstream package to review and install the complete skill.',
  'external_source',
  '0.00',
  'caution',
  'Requests repository read, shell, and report-write access. Review its allowed tools before running on sensitive code.',
  'approved',
  0,
  '2026-07-22T00:00:00.000Z',
  '2026-06-30T15:14:46.000Z',
  'external_source',
  'curated',
  0,
  'https://github.com/trailofbits/skills/tree/cfe5d7b1619e47fb5b38b7e2561dad7e5f1e89af/plugins/differential-review/skills/differential-review',
  'cfe5d7b1619e47fb5b38b7e2561dad7e5f1e89af',
  'plugins/differential-review/skills/differential-review'
),
(
  'curated_tob_supply_chain_cfe5d7b',
  'supply-chain-risk-auditor',
  'Supply Chain Risk Audit',
  'Flags dependencies with maintenance, ownership, popularity, release, and high-risk capability signals that deserve deeper review.',
  'Security',
  '["supply-chain","dependencies","security","trail-of-bits"]',
  'git-cfe5d7b',
  'CC-BY-SA-4.0',
  'Trail of Bits',
  'GOKUI community-curated source listing. Open the pinned upstream package to review and install the complete skill.',
  'external_source',
  '0.00',
  'caution',
  'Requests repository, shell, and report-write access. It is a risk triage workflow, not an active vulnerability scanner.',
  'approved',
  0,
  '2026-07-22T00:00:00.000Z',
  '2026-06-30T15:14:46.000Z',
  'external_source',
  'curated',
  0,
  'https://github.com/trailofbits/skills/tree/cfe5d7b1619e47fb5b38b7e2561dad7e5f1e89af/plugins/supply-chain-risk-auditor/skills/supply-chain-risk-auditor',
  'cfe5d7b1619e47fb5b38b7e2561dad7e5f1e89af',
  'plugins/supply-chain-risk-auditor/skills/supply-chain-risk-auditor'
),
(
  'curated_anthropic_frontend_design_fa0fa64',
  'distinctive-frontend-design',
  'Distinctive Frontend Design',
  'Pushes agents to build intentional visual systems, typography, layouts, and memorable signature details instead of generic template UI.',
  'Design',
  '["frontend","visual-design","typography","anthropic"]',
  'git-fa0fa64',
  'Apache-2.0',
  'Anthropic',
  'GOKUI community-curated source listing. Open the pinned upstream package to review and install the complete skill.',
  'external_source',
  '0.00',
  'normal',
  'Instruction-only package under the Apache-2.0 license included in the reviewed skill directory.',
  'approved',
  0,
  '2026-07-22T00:00:00.000Z',
  '2026-07-17T02:47:37.000Z',
  'external_source',
  'curated',
  0,
  'https://github.com/anthropics/skills/tree/fa0fa64bdc967915dc8399e803be67759e1e62b8/skills/frontend-design',
  'fa0fa64bdc967915dc8399e803be67759e1e62b8',
  'skills/frontend-design'
),
(
  'curated_anthropic_mcp_builder_fa0fa64',
  'mcp-server-builder',
  'MCP Server Builder',
  'Guides the design, implementation, testing, and evaluation of Model Context Protocol servers for external APIs and services.',
  'Agent infrastructure',
  '["mcp","tools","api-integration","anthropic"]',
  'git-fa0fa64',
  'Apache-2.0',
  'Anthropic',
  'GOKUI community-curated source listing. Open the pinned upstream package to review and install the complete skill.',
  'external_source',
  '0.00',
  'caution',
  'Includes Python evaluation helpers and guides external-service integrations; inspect code and keep credentials least-privileged.',
  'approved',
  0,
  '2026-07-22T00:00:00.000Z',
  '2026-07-17T02:47:37.000Z',
  'external_source',
  'curated',
  0,
  'https://github.com/anthropics/skills/tree/fa0fa64bdc967915dc8399e803be67759e1e62b8/skills/mcp-builder',
  'fa0fa64bdc967915dc8399e803be67759e1e62b8',
  'skills/mcp-builder'
),
(
  'curated_elastic_llm_obs_96736be',
  'llm-agent-observability',
  'LLM & Agent Observability',
  'Investigates model latency, token cost, response quality, traces, and multi-step agent workflows using data already ingested into Elastic.',
  'Observability',
  '["llm","agents","observability","elastic"]',
  '0.1.0',
  'Apache-2.0',
  'Elastic',
  'GOKUI community-curated source listing. Open the pinned upstream package to review and install the complete skill.',
  'external_source',
  '0.00',
  'caution',
  'Queries operational telemetry that may contain sensitive prompts or identifiers; use scoped read access and redact outputs.',
  'approved',
  0,
  '2026-07-22T00:00:00.000Z',
  '2026-07-01T07:53:25.000Z',
  'external_source',
  'curated',
  0,
  'https://github.com/elastic/agent-skills/tree/96736bec4aa27f236580a3fefc4b14582f0f8aa0/skills/observability/llm-obs',
  '96736bec4aa27f236580a3fefc4b14582f0f8aa0',
  'skills/observability/llm-obs'
),
(
  'curated_nvidia_rag_blueprint_fdbb8ed',
  'nvidia-rag-blueprint',
  'NVIDIA RAG Blueprint',
  'Routes deployment, configuration, troubleshooting, evaluation, and operations work across NVIDIA RAG Blueprint environments.',
  'AI engineering',
  '["rag","nvidia","deployment","ai-infrastructure"]',
  '2.6.0',
  'CC-BY-4.0 / Apache-2.0',
  'NVIDIA',
  'GOKUI community-curated source listing. Open the pinned upstream package to review and install the complete skill.',
  'external_source',
  '0.00',
  'high',
  'High-privilege operations skill: referenced workflows can deploy, reconfigure, restart, or remove infrastructure. Require human confirmation and scoped credentials.',
  'approved',
  0,
  '2026-07-22T00:00:00.000Z',
  '2026-07-21T19:13:49.000Z',
  'external_source',
  'curated',
  0,
  'https://github.com/NVIDIA/skills/tree/fdbb8edec29b72a482140c1d14e4484a600739de/skills/rag-blueprint',
  'fdbb8edec29b72a482140c1d14e4484a600739de',
  'skills/rag-blueprint'
);
